# Generated by Django 2.2.1 on 2019-05-12 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='sound',
            name='character',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sounds.Character'),
        ),
    ]
