# Generated by Django 2.2.1 on 2019-05-12 21:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sounds', '0002_auto_20190512_1304'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sound',
            name='charId',
        ),
    ]
